Sarif reporting - temp 2
mercedes-benz/zap-extensions pull request #8
Opened 2022-06-01 06:40 UTC by de-jcup

Just to identify current changes between main and sarif-reporting branch

2022-06-01 17:06 UTC, Jeeppler requested changes
See comments.

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifBigContentShrinker.java
> +        boolean shrinkMarketAtBeginning = true;
```suggestion
        boolean shrinkMarkerAtBeginning = true;
```

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifBinaryContentDetector.java
> +        return !(contentTypeLowerCased.startsWith("text")
This is hard to read and evaluate as many things are going on here. I would prefer the use of `if` and `else`, even if this increases the verbosity.

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifReportDataSupport.java
> +        List<SarifResult> results = new ArrayList<>();
I would prefer a linked list rather than a ArrayList. The reason, being that for a array list to grow beyond it's initial capacity, a memory copy needs to happen (memory reallocation). A linked list instead can simply grow.

Or in this case move the statement below `allAlerts` and initialize the arraylist with the size of `allAlerts`.

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifReportDataSupport.java
> +        List<Alert> list = new ArrayList<>();
I would prefer a linked list rather than a ArrayList. The reason, being that for a array list to grow beyond it's initial capacity, a memory copy needs to happen (memory reallocation). A linked list instead can simply grow.

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifResult.java
> +                            alert.getEvidence(), MAX_ALLOWED_EVICENCE_SNIPPET_SIZE);
```suggestion
                            alert.getEvidence(), MAX_ALLOWED_EVIDENCE_SNIPPET_SIZE);
```

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifToolData.java
> +    private static final SarifToolDataProvider CWE_WITH_4_4_TAXONOMY =
The CWE list is now at 4.7: https://cwe.mitre.org/data/downloads.html

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifBase64EncoderTest.java
> +    void testdataResultsInCorrectBase64Value() {
Please add a test which contains an emoji. Emojis are not just ASCII symbols. Emojis are an easy way to test UTF-8/Unicode handling.

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifBigContentShrinkerTest.java
> +    @CsvSource({
What happens in case of `0` or `-2`?

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifReportIntegrationTest.java
> +    private void assertRuleHasCweEntrAndGuidsNotDuplicated(
```suggestion
    private void assertRuleHasCweEntryAndGuidsNotDuplicated(
```

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifReportIntegrationTest.java
> +        JsonNode relationShips = rule.get("relationships");
```suggestion
        JsonNode relationships = rule.get("relationships");
```

2022-06-01 17:06 UTC, Jeeppler commented on addOns/reports/src/test/java/org/zaproxy/addon/reports/sarif/SarifReportIntegrationTest.java
> +        for (JsonNode relationShip : relationShipsArray) {
```suggestion
        for (JsonNode relationship : relationshipsArray) {
```

2022-09-29 12:37 UTC, de-jcup commented on addOns/reports/src/main/java/org/zaproxy/addon/reports/sarif/SarifReportDataSupport.java
> +        List<SarifResult> results = new ArrayList<>();
Linked lists have some caveats as well - the sorting done at the end will be much slower compared to array list.
But I will init the array list with the correct initial capacity - as you suggested.

2022-09-29 15:09 UTC, merged